### ISSUE TITLE
Ajouter une FAQ présentant les erreurs de visualisation

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/doc-opencatalog#1]
A la manière de [celle de la doc du scan](https://help.isogeo.com/scan/fr/support/faq.html), ajouter une page FAQ en annexe présentant les erreurs fréquentes liées à la visualisation des services notamment

- La donnée n'a pas pu être récupérée : C'est à dire que le serveur a pas pu être joint
- Des données n'ont pas de géométrie : C'est à dire champs geom vide
- Impossible de charger les données : C'est à dire serveur disponible mais rien n'est reçu par OpenLayers.

**Comment by leodarengosse** [comment]
Attention, il y a quelques fautes d'orthographe ;)

**Comment by jgrosmaire** [comment]
En effet ... Normalement c'est bon maintenant
